// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (cart_id, variant_id, qty)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id)
DO UPDATE SET qty = cart_items.qty + EXCLUDED.qty
RETURNING id, cart_id, variant_id, qty, created_at
`

type AddCartItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Qty       int32     `json:"qty"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, addCartItem, arg.CartID, arg.VariantID, arg.Qty)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Qty,
		&i.CreatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearCart, cartID)
	return err
}

const getCartWithItems = `-- name: GetCartWithItems :many
SELECT
    ci.id,
    ci.qty,
    v.id AS variant_id,
    v.name AS variant_name,
    v.price,
    v.stock,
    v.sku,
    p.id AS product_id,
    p.name AS product_name,
    p.slug AS product_slug,
    p.images
FROM cart_items ci
JOIN variants v ON v.id = ci.variant_id
JOIN products p ON p.id = v.product_id
WHERE ci.cart_id = $1
`

type GetCartWithItemsRow struct {
	ID          uuid.UUID `json:"id"`
	Qty         int32     `json:"qty"`
	VariantID   uuid.UUID `json:"variant_id"`
	VariantName string    `json:"variant_name"`
	Price       int32     `json:"price"`
	Stock       int32     `json:"stock"`
	Sku         string    `json:"sku"`
	ProductID   uuid.UUID `json:"product_id"`
	ProductName string    `json:"product_name"`
	ProductSlug string    `json:"product_slug"`
	Images      []string  `json:"images"`
}

func (q *Queries) GetCartWithItems(ctx context.Context, cartID uuid.UUID) ([]GetCartWithItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCartWithItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartWithItemsRow
	for rows.Next() {
		var i GetCartWithItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qty,
			&i.VariantID,
			&i.VariantName,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSlug,
			pq.Array(&i.Images),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateCart = `-- name: GetOrCreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
ON CONFLICT (user_id)
DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) GetOrCreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE id = $1 AND cart_id = $2
`

type RemoveCartItemParams struct {
	ID     uuid.UUID `json:"id"`
	CartID uuid.UUID `json:"cart_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.ExecContext(ctx, removeCartItem, arg.ID, arg.CartID)
	return err
}
