// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total, expires_at, shipping_address)
VALUES ($1, 'pending', $2, NOW() + INTERVAL '15 minutes', $3)
RETURNING id, user_id, status, total, expires_at, created_at, updated_at, shipping_address
`

type CreateOrderParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	Total           int32          `json:"total"`
	ShippingAddress sql.NullString `json:"shipping_address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.Total, arg.ShippingAddress)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, variant_id, qty, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, variant_id, qty, price, created_at
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Qty       int32     `json:"qty"`
	Price     int32     `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Qty,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Qty,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.id, o.user_id, o.status, o.total, o.expires_at, o.created_at, o.updated_at, o.shipping_address, COALESCE(
    json_agg(oi ORDER BY oi.created_at)
    FILTER (WHERE oi.id IS NOT NULL),
    '[]'
) AS items
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.id = $1
GROUP BY o.id
`

type GetOrderByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Status          OrderStatus    `json:"status"`
	Total           int32          `json:"total"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ShippingAddress sql.NullString `json:"shipping_address"`
	Items           interface{}    `json:"items"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
		&i.Items,
	)
	return i, err
}

const getPendingOrderByUserID = `-- name: GetPendingOrderByUserID :one
SELECT id, user_id, status, total, expires_at, created_at, updated_at, shipping_address
FROM orders
WHERE user_id = $1
AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingOrderByUserID(ctx context.Context, userID uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getPendingOrderByUserID, userID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT id, user_id, status, total, expires_at, created_at, updated_at, shipping_address FROM orders
WHERE status = 'pending'
AND expires_at < NOW()
`

func (q *Queries) ListExpiredPendingOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, variant_id, qty, price, created_at
FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Qty,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersAdmin = `-- name: ListOrdersAdmin :many
SELECT id, user_id, status, total, expires_at, created_at, updated_at, shipping_address FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersAdmin(ctx context.Context, arg ListOrdersAdminParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, status, total, shipping_address, expires_at, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListOrdersByUserIDRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Status          OrderStatus    `json:"status"`
	Total           int32          `json:"total"`
	ShippingAddress sql.NullString `json:"shipping_address"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]ListOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserIDRow
	for rows.Next() {
		var i ListOrdersByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.ShippingAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1::order_status,
    updated_at = NOW()
WHERE id = $2
AND (
    (status = 'pending'   AND $1::text IN ('paid', 'expired', 'cancelled'))
    OR (status = 'paid'   AND $1::text IN ('shipped', 'cancelled'))
    OR (status = 'shipped' AND $1::text IN ('delivered', 'cancelled'))
)
RETURNING id, user_id, status, total, expires_at, created_at, updated_at, shipping_address
`

type UpdateOrderStatusParams struct {
	Status OrderStatus `json:"status"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingAddress,
	)
	return i, err
}
