// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, razorpay_order_id, amount, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, provider, status, razorpay_order_id, razorpay_payment_id, amount, currency, reference, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID         uuid.UUID      `json:"order_id"`
	RazorpayOrderID sql.NullString `json:"razorpay_order_id"`
	Amount          int32          `json:"amount"`
	Currency        string         `json:"currency"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.RazorpayOrderID,
		arg.Amount,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.Status,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByRazorpayOrderID = `-- name: GetPaymentByRazorpayOrderID :one
SELECT id, order_id, provider, status, razorpay_order_id, razorpay_payment_id, amount, currency, reference, created_at, updated_at FROM payments
WHERE razorpay_order_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByRazorpayOrderID(ctx context.Context, razorpayOrderID sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByRazorpayOrderID, razorpayOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.Status,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $1,
    razorpay_payment_id = $2,
    reference = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, order_id, provider, status, razorpay_order_id, razorpay_payment_id, amount, currency, reference, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status            PaymentStatus  `json:"status"`
	RazorpayPaymentID sql.NullString `json:"razorpay_payment_id"`
	Reference         sql.NullString `json:"reference"`
	ID                uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus,
		arg.Status,
		arg.RazorpayPaymentID,
		arg.Reference,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.Status,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
