// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  slug,
  description,
  category,
  images
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, name, slug, description, images, active, created_at, updated_at, category
`

type CreateProductParams struct {
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Images      []string `json:"images"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		pq.Array(arg.Images),
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one

INSERT INTO variants (
  product_id,
  sku,
  name,
  price,
  stock
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Sku       string    `json:"sku"`
	Name      string    `json:"name"`
	Price     int32     `json:"price"`
	Stock     int32     `json:"stock"`
}

// =========================================
// VARIANTS
// =========================================
func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :one
UPDATE products
SET active = false,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, images, active, created_at, updated_at, category
`

func (q *Queries) DeactivateProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, deactivateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const getProductByCategoryAndSlug = `-- name: GetProductByCategoryAndSlug :one
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, p.category, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.slug = $1
  AND p.category = $2
  AND p.active = true
GROUP BY p.id
`

type GetProductByCategoryAndSlugParams struct {
	Slug     string `json:"slug"`
	Category string `json:"category"`
}

type GetProductByCategoryAndSlugRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Category    string      `json:"category"`
	Variants    interface{} `json:"variants"`
}

// STRICT VERSION (RECOMMENDED)
func (q *Queries) GetProductByCategoryAndSlug(ctx context.Context, arg GetProductByCategoryAndSlugParams) (GetProductByCategoryAndSlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByCategoryAndSlug, arg.Slug, arg.Category)
	var i GetProductByCategoryAndSlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Variants,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, slug, description, images, active, created_at, updated_at, category
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, p.category, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.slug = $1
  AND p.active = true
GROUP BY p.id
`

type GetProductBySlugRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Category    string      `json:"category"`
	Variants    interface{} `json:"variants"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Variants,
	)
	return i, err
}

const getProductWithVariantsByID = `-- name: GetProductWithVariantsByID :one
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, p.category, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetProductWithVariantsByIDRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Category    string      `json:"category"`
	Variants    interface{} `json:"variants"`
}

func (q *Queries) GetProductWithVariantsByID(ctx context.Context, id uuid.UUID) (GetProductWithVariantsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductWithVariantsByID, id)
	var i GetProductWithVariantsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Variants,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, sku, name, price, stock, created_at, updated_at
FROM variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRowContext(ctx, getVariantByID, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many

SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, p.category, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.active = true
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Category    string      `json:"category"`
	Variants    interface{} `json:"variants"`
}

// =========================================
// PRODUCTS + VARIANTS (PUBLIC)
// =========================================
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			pq.Array(&i.Images),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAdmin = `-- name: ListProductsAdmin :many

SELECT id, name, slug, description, images, active, created_at, updated_at, category
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// =========================================
// PRODUCTS (ADMIN)
// =========================================
func (q *Queries) ListProductsAdmin(ctx context.Context, arg ListProductsAdminParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			pq.Array(&i.Images),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, p.category, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.active = true
  AND p.category = $3
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsByCategoryParams struct {
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
	Category string `json:"category"`
}

type ListProductsByCategoryRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Category    string      `json:"category"`
	Variants    interface{} `json:"variants"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			pq.Array(&i.Images),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, name, price, stock, created_at, updated_at
FROM variants
WHERE product_id = $1
ORDER BY created_at
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.QueryContext(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVariantStock = `-- name: LockVariantStock :one

UPDATE variants
SET stock = stock - $1
WHERE id = $2
  AND stock >= $1
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type LockVariantStockParams struct {
	Qty int32     `json:"qty"`
	ID  uuid.UUID `json:"id"`
}

// =========================================
// STOCK MANAGEMENT
// =========================================
func (q *Queries) LockVariantStock(ctx context.Context, arg LockVariantStockParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, lockVariantStock, arg.Qty, arg.ID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseVariantStock = `-- name: ReleaseVariantStock :exec
UPDATE variants
SET stock = stock + $1
WHERE id = $2
`

type ReleaseVariantStockParams struct {
	Qty int32     `json:"qty"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) ReleaseVariantStock(ctx context.Context, arg ReleaseVariantStockParams) error {
	_, err := q.db.ExecContext(ctx, releaseVariantStock, arg.Qty, arg.ID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    description = $2,
    images = $3,
    category = $4,
    active = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, name, slug, description, images, active, created_at, updated_at, category
`

type UpdateProductParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Images      []string  `json:"images"`
	Category    string    `json:"category"`
	Active      bool      `json:"active"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		pq.Array(arg.Images),
		arg.Category,
		arg.Active,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants
SET name = $1,
    price = $2,
    stock = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type UpdateVariantParams struct {
	Name  string    `json:"name"`
	Price int32     `json:"price"`
	Stock int32     `json:"stock"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, updateVariant,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
