// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, slug, description, images)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, images, active, created_at, updated_at
`

type CreateProductParams struct {
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Images      []string `json:"images"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		pq.Array(arg.Images),
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (product_id, sku, name, price, stock)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Sku       string    `json:"sku"`
	Name      string    `json:"name"`
	Price     int32     `json:"price"`
	Stock     int32     `json:"stock"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.slug = $1 AND p.active = true
GROUP BY p.id
`

type GetProductBySlugRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Variants    interface{} `json:"variants"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variants,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, sku, name, price, stock, created_at, updated_at FROM variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRowContext(ctx, getVariantByID, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.slug, p.description, p.images, p.active, p.created_at, p.updated_at, COALESCE(
    json_agg(v ORDER BY v.created_at)
    FILTER (WHERE v.id IS NOT NULL),
    '[]'
) AS variants
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
WHERE p.active = true
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Images      []string    `json:"images"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Variants    interface{} `json:"variants"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			pq.Array(&i.Images),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAdmin = `-- name: ListProductsAdmin :many
SELECT id, name, slug, description, images, active, created_at, updated_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductsAdmin(ctx context.Context, arg ListProductsAdminParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			pq.Array(&i.Images),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVariantStock = `-- name: LockVariantStock :one
UPDATE variants
SET stock = stock - $1
WHERE id = $2 AND stock >= $1
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type LockVariantStockParams struct {
	Qty int32     `json:"qty"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) LockVariantStock(ctx context.Context, arg LockVariantStockParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, lockVariantStock, arg.Qty, arg.ID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseVariantStock = `-- name: ReleaseVariantStock :exec
UPDATE variants
SET stock = stock + $1
WHERE id = $2
`

type ReleaseVariantStockParams struct {
	Qty int32     `json:"qty"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) ReleaseVariantStock(ctx context.Context, arg ReleaseVariantStockParams) error {
	_, err := q.db.ExecContext(ctx, releaseVariantStock, arg.Qty, arg.ID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    description = $2,
    images = $3,
    active = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, name, slug, description, images, active, created_at, updated_at
`

type UpdateProductParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Images      []string  `json:"images"`
	Active      bool      `json:"active"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		pq.Array(arg.Images),
		arg.Active,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		pq.Array(&i.Images),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants
SET name = $1,
    price = $2,
    stock = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, product_id, sku, name, price, stock, created_at, updated_at
`

type UpdateVariantParams struct {
	Name  string    `json:"name"`
	Price int32     `json:"price"`
	Stock int32     `json:"stock"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRowContext(ctx, updateVariant,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
