// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearCart(ctx context.Context, cartID uuid.UUID) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error)
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	GetCartWithItems(ctx context.Context, cartID uuid.UUID) ([]GetCartWithItemsRow, error)
	GetOrCreateCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error)
	GetPaymentByRazorpayOrderID(ctx context.Context, razorpayOrderID sql.NullString) (Payment, error)
	GetPendingOrderByUserID(ctx context.Context, userID uuid.UUID) (Order, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error)
	ListExpiredPendingOrders(ctx context.Context) ([]Order, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersAdmin(ctx context.Context, arg ListOrdersAdminParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsAdmin(ctx context.Context, arg ListProductsAdminParams) ([]Product, error)
	ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]Variant, error)
	LockVariantStock(ctx context.Context, arg LockVariantStockParams) (Variant, error)
	ReleaseVariantStock(ctx context.Context, arg ReleaseVariantStockParams) error
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error)
}

var _ Querier = (*Queries)(nil)
